### Задание 1

In [142]:
import numpy as np

In [4]:
N=20
N=np.array(range(20))
N[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### Задание 2

In [5]:
m = np.diag(np.arange(15,0,-1), k=0)
m_diag = np.asarray(m)
print(m)

print('Сумма значений по диагонали:', np.trace(m_diag))

[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 11  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]]
Сумма значений по диагонали: 120


### Задание 3

In [6]:
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3
from numpy import linalg

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
 
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
#Вручную тоже посчитано, все верно

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задание 4



In [103]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ] 
)

In [104]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [173]:
def cosine( row, next_user_stats ):
    
        row_Length = np.linalg.norm( row )
        next_user_stats_Length = np.linalg.norm( next_user_stats )
        result = np.dot( row, next_user_stats ) / ( row_Length * next_user_stats_Length )
        return print(result, sep='\n')
                
cos_row = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)


0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.8799999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
